### ISSUE TITLE
Possible to download on install?

### ISSUE THREAD

**Issue by fakerybakery** [polm/unidic-py#14]
Hi, thanks for releasing Unidic! Is there any chance it would be possible to auto-download the dictionary when installing via pip? Thanks!

**Comment by polm** [comment]
I think it is possible since setup.py can run arbitrary code, but it's a bad idea for several reasons.

First, note it is not possible to host this file on PyPI directly, due to their file size limits. (It is possible to request an exception, but this is not the kind of package they provide exceptions for.) Given that, downloading from an external server is required. If the external server is down or inaccessible at install time, there would be no workaround. 

If the dictionary is downloaded at install time, it would be necessary to automatically choose the version to download, which makes actual version control harder.

Note that in general Python packaging is moving away from allowing arbitrary code to be executed at install time, as it prevents optimization and poses a security risk. So any solution would be fragile and likely to work against pip.

It would also be unacceptable to change the current library to work this way, as it would be a large behavior change. 

-----

Those are some reasons not to change it. As far as I'm aware the only reason it would be nice to download automatically is for convenience. If you have other reasons please do let me know, but for now I will close this as won't-fix.
