### ISSUE TITLE
Potential inconsistency in the number lemmas

### ISSUE THREAD

**Issue by srctaha** [polm/unidic-py#2]
```python
import fugashi
import unidic
tagger = fugashi.Tagger('-d{}'.format(unidic.DICDIR))

text = '2.5.750.10 親会社が子会社に対する支配を喪失する方法は様々である。'
for word in tagger(text):
    print(word.surface, word.feature.lemma)
```
returns
```python
2 None
. ．
5 None
. ．
750 None
. ．
10 テン-ten
...
```

Would the _differences_ in the lemmas of 2,5,750, and 10 be an expected behavior?

<details>
  <summary>Setup</summary>

  - fugashi==1.0.4
  - unidic==1.0.2
  - python==3.8.3
</details>

**Comment by polm** [comment]
This is somewhat unexpected. It is definitely not good.

This happens because in 1.0.2 single-digit numeric entries were removed to avoid numbers being tokenized into individual digits. While it looks like the tokenization issue is fixed, this issue with strictly numeric tokens remains. 

I'll look at removing all numeric-only tokens from the dictionary.

**Comment by polm** [comment]
Sorry for taking so long to get on this, but in the soon-to-be-released next version of the dictionary all purely numeric tokens will be removed (and thus have no lemmas). 

You can see the scripts used to prepare the dictionary here.

https://github.com/polm/unidic-py/tree/master/extras

I'll go ahead and close this.
