### ISSUE TITLE
Unexpected lemmas

### ISSUE THREAD

**Issue by srctaha** [polm/unidic-py#7]
This is not to report an issue about the package, but rather, to bring an unexpected fact about `unidic-cwj-2.3.0/lex.csv` into your attention.

Within the CSV file, there are `57,608` entries for which the 12th column (lemma) includes hyphen (-). Examples:
- `アシスタント`: `アイスランド-Iceland`
- `アシスタント`: `アシスタント-assistant`
- `アイブ`: `アイブ-I've`
- `10`: `テン-ten`

Interestingly, the lemma for `9` is given as `九`.

I was wondering if removing anything after the hyphens would be meaningful.

**Comment by polm** [comment]
Thanks for the report. 

This is an undocumented but pretty consistent feature of UniDic where loanwords (外来語) have the "foreign" spelling (or at least the English one) included after the hyphen. This feature is used extensively in [cutlet](https://github.com/polm/cutlet), so that `セール開催中` would be `sale kaisaichuu` rather than `se-ru kaisaichuu` (you can turn it off if you want though).

This doesn't affect the ability of lemmas to be used as unique identifiers for different forms of words; for example, both コンピューター and コンピュータ (no final long vowel) have the lemma `コンピューター-computer`. 

One thing to be aware of is that there are a few exceptions to this regarding lemmas with hyphens.

- A small number of lemmas have 外国 instead of foreign spelling, like ジル (lemma: `ジル-外国`). Reason is unclear, possibly ambiguity. 
- A very small number of words (maybe three?) have lemmas like `私-代名詞`.

The numbers are just weird, which is part of why I remove numeric entries when redistributing UniDic. 

Let me know if you have any other questions about this.

**Comment by srctaha** [comment]
Thank you for the information. As you are already aware of this UniDic feature, please allow me to close this issue.
